import React, { Component } from "react";
import { nanoid } from "nanoid";
import "./index.css";

export default class Header extends Component {
  handleKeyUp = (event) => {
    // get keyCode and target from event
    const { keyCode, target } = event;
    // if the Enter key is not pressed, don't do anything
    if (keyCode !== 13) return;
    // if task name is empty, alert and don't do anything even Enter key is pressed
    if (target.value.trim() === "") {
      alert("Task name cannot be empty");
      return;
    }
    // construct a new todo Obj
    const todoObj = { id: nanoid(), name: target.value, done: false }; // id generated by nanoid
    // pass todoObj to App component
    this.props.addTodo(todoObj);
    // empty the input area
    target.value = "";
  };

  render() {
    return (
      <div className="todo-header">
        <input
          type="text"
          placeholder="Input task name, press Enter to confirm"
          onKeyUp={this.handleKeyUp}
        ></input>
      </div>
    );
  }
}
